// Post-checkout licence claim contract
//
// A buyer completes Paddle's overlay checkout and lands on the site's success
// page. This contract is how they exchange that completed purchase for the
// licence key it minted, without an account (INV-001 keeps Proso signup-free).
//
// WHY THE TRANSACTION ID IS NOT THE CREDENTIAL
//
// Paddle appends `_ptxn=<transaction-id>` to checkout and success URLs by
// design (https://developer.paddle.com/build/transactions/pass-transaction-checkout/).
// A value that Paddle deliberately puts in a URL lands in browser history,
// referrer headers, proxy logs, screenshots and support transcripts. It is
// routing metadata. Handing a reusable licence key to whoever presents one is
// a security defect, not a convenience.
//
// So the purchase carries its own secret, generated by the buyer's browser
// before checkout opens:
//
//   1. At the buy click the site generates 32 random bytes (Web Crypto),
//      base64url-encodes them as `claimSecret`, and keeps the raw value in
//      that tab's `sessionStorage`. It never leaves the browser except in
//      step 3.
//   2. Only `SHA-256(claimSecret)`, lowercase hex, travels to Paddle as
//      `custom_data.license_claim_hash`. Paddle copies custom data onto the
//      signed transaction and subscription events, so the server persists the
//      hash alongside `paddleTransactionId`. The raw secret is never stored.
//   3. The success page POSTs `{ transactionId, claimSecret }`. The server
//      hashes the secret and compares it to the persisted hash in constant
//      time. The transaction id routes; the secret authorises.
//
// Consequences the server side must honour:
//   - A wrong or absent claim secret NEVER returns a key.
//   - There is exactly ONE unavailable answer: 202 with a `pending` body. An
//     unknown transaction id, a transaction whose webhook is still in flight,
//     and a transaction presented with the wrong claim secret are answered
//     identically. No 403, no 404, no distinct message, no timing tell — the
//     endpoint must never confirm that a given transaction id exists.
//   - Rate limiting is mandatory, not optional; it is what bounds abuse, since
//     a 256-bit claim secret already makes guessing hopeless.
//   - `custom_data.tier` is client-controlled and MUST NOT decide entitlement.
//     It travels for diagnostics only; the tier a buyer receives is derived
//     server-side from the Paddle price id, and an unknown price id is a hard
//     failure rather than a default.
//
// Consumers:
//   - packages/site/assets/js/checkout.js  — mints the claim secret at buy time
//   - packages/site/assets/js/success.js   — redeems it (hand-written checks;
//     the static site has no bundler and cannot import zod)
//   - packages/server                      — issuance endpoint (Feature 148)
//
//   POST {apiBaseUrl}/api/v1/license/by-transaction
//   body: LicenseClaimRequest
//   200  → LicenseIssued   (this claim authorises this purchase)
//   202  → LicensePending  (everything else: unknown, in flight, or wrong claim)

import { z } from 'zod';
import { SubscriptionTier } from '../domain/subscription.js';

/** Route for the claim endpoint, relative to the API base URL. */
export const LICENSE_BY_TRANSACTION_PATH = '/api/v1/license/by-transaction';

/** Bytes of entropy in a claim secret before base64url encoding. */
export const LICENSE_CLAIM_SECRET_BYTES = 32;

/**
 * Key under which the site parks the raw claim secret between the buy click
 * and the success page. `sessionStorage`, so it dies with the tab.
 */
export const LICENSE_CLAIM_STORAGE_KEY = 'proso.license-claim-secret';

/**
 * Paddle `custom_data` field carrying `SHA-256(claimSecret)` as lowercase hex.
 * Named in snake_case because that is how it appears in webhook payloads.
 */
export const LICENSE_CLAIM_HASH_FIELD = 'license_claim_hash';

/** Lowercase hex SHA-256 digest — what the server persists and compares. */
export const LicenseClaimHashSchema = z.string().regex(/^[0-9a-f]{64}$/);

export const LicenseClaimRequestSchema = z.object({
  /** Paddle transaction id, e.g. `txn_01hv…`. Routing only — never an authoriser. */
  transactionId: z.string().min(1),
  /** base64url of 32 random bytes, minted by the buyer's browser at checkout time. */
  claimSecret: z.string().min(1),
});

export type LicenseClaimRequestParsed = z.infer<typeof LicenseClaimRequestSchema>;

/** The purchase produced a key, and the presented claim secret authorises it. */
export const LicenseIssuedSchema = z.object({
  status: z.literal('issued'),
  licenseKey: z.string().min(1),
  tier: z.nativeEnum(SubscriptionTier),
  /** ISO-8601 instant the key was minted. */
  issuedAt: z.string().datetime(),
});

export type LicenseIssuedParsed = z.infer<typeof LicenseIssuedSchema>;

/**
 * No key is available to this caller. This is the ONLY unavailable answer, and
 * it is deliberately ambiguous: the webhook may still be in flight, the
 * transaction may not exist, or the claim secret may be wrong. A caller cannot
 * tell which, so the endpoint is not an oracle for which purchases exist.
 *
 * A caller that keeps polling on a claim it cannot satisfy simply times out.
 */
export const LicensePendingSchema = z.object({
  status: z.literal('pending'),
  /** How long the caller should wait before asking again. */
  retryAfterMs: z.number().int().positive(),
});

export type LicensePendingParsed = z.infer<typeof LicensePendingSchema>;

export const LicenseClaimResponseSchema = z.discriminatedUnion('status', [
  LicenseIssuedSchema,
  LicensePendingSchema,
]);

export type LicenseClaimResponseParsed = z.infer<typeof LicenseClaimResponseSchema>;
