coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 2%
    patch:
      default:
        target: 80%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

flags:
  extension:
    paths:
      - packages/extension/src/
    carryforward: true
  server:
    paths:
      - packages/server/src/
    carryforward: true
