# Offline unit tests. The provider is mocked, so these run without credentials
# and assert only on values known at plan time — which is exactly where the two
# silent failure modes live.

mock_provider "aws" {
  mock_data "aws_region" {
    defaults = {
      id     = "us-east-1"
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "699475944323"
      id         = "699475944323"
      arn        = "arn:aws:iam::699475944323:root"
    }
  }
}

variables {
  name               = "proso-site"
  domain_names       = ["proso.com.br"]
  release_source_dir = "./tests/fixtures/site"
}

run "origin_bucket_is_not_public" {
  command = plan

  assert {
    condition     = aws_s3_bucket_public_access_block.site.block_public_acls
    error_message = "public ACLs are not blocked on the origin bucket"
  }

  assert {
    condition     = aws_s3_bucket_public_access_block.site.block_public_policy
    error_message = "a public bucket policy could still be attached to the origin bucket"
  }

  assert {
    condition     = aws_s3_bucket_public_access_block.site.ignore_public_acls
    error_message = "existing public ACLs would still be honoured on the origin bucket"
  }

  assert {
    condition     = aws_s3_bucket_public_access_block.site.restrict_public_buckets
    error_message = "the origin bucket is not restricted to authorised principals"
  }

  assert {
    condition     = aws_s3_bucket_ownership_controls.site.rule[0].object_ownership == "BucketOwnerEnforced"
    error_message = "ACLs are still enabled on the origin bucket; an upload could grant public-read"
  }

  assert {
    condition = alltrue([
      aws_s3_bucket_public_access_block.logs.block_public_acls,
      aws_s3_bucket_public_access_block.logs.block_public_policy,
      aws_s3_bucket_public_access_block.logs.ignore_public_acls,
      aws_s3_bucket_public_access_block.logs.restrict_public_buckets,
    ])
    error_message = "the access log bucket is not fully blocked from public access"
  }
}

run "origin_is_reached_only_through_oac" {
  command = plan

  # The OAC id is generated by AWS, so pin it to make the wiring visible at plan
  # time: the distribution must carry exactly this id, not "" and not another.
  override_resource {
    target          = aws_cloudfront_origin_access_control.this
    override_during = plan
    values = {
      id = "E2MOCKOACID"
    }
  }

  # origin is a set, so it has no addressable index.
  assert {
    condition = alltrue([
      for origin in aws_cloudfront_distribution.this.origin :
      origin.origin_access_control_id == "E2MOCKOACID"
    ])
    error_message = "an origin is not wired to this module's Origin Access Control"
  }

  assert {
    condition     = length(aws_cloudfront_distribution.this.origin) == 1
    error_message = "expected exactly one origin, so the OAC assertion above covers the whole distribution"
  }

  assert {
    condition     = aws_cloudfront_origin_access_control.this.origin_access_control_origin_type == "s3"
    error_message = "the OAC is not configured for an S3 origin"
  }

  assert {
    condition     = aws_cloudfront_origin_access_control.this.signing_behavior == "always"
    error_message = "the OAC does not always sign, so unsigned requests would reach the origin"
  }

  assert {
    condition     = aws_cloudfront_origin_access_control.this.signing_protocol == "sigv4"
    error_message = "the OAC does not sign with SigV4"
  }

  assert {
    condition     = aws_cloudfront_distribution.this.default_cache_behavior[0].viewer_protocol_policy == "redirect-to-https"
    error_message = "viewers are not redirected to HTTPS"
  }
}

run "default_root_object_is_set" {
  command = plan

  assert {
    condition     = aws_cloudfront_distribution.this.default_root_object == "index.html"
    error_message = "no default root object: a request to / would return the origin's access-denied response instead of the site"
  }
}

run "certificate_is_requested_in_us_east_1" {
  command = plan

  assert {
    condition     = data.aws_region.current.region == "us-east-1"
    error_message = "the module is not running in us-east-1, where CloudFront reads its certificate from"
  }

  assert {
    condition     = aws_acm_certificate.this.validation_method == "DNS"
    error_message = "the certificate does not use DNS validation, which is the only method available with DNS at Cloudflare"
  }

  assert {
    condition     = aws_acm_certificate.this.domain_name == "proso.com.br"
    error_message = "the certificate does not cover the primary domain"
  }
}

# Falsifies the precondition rather than the happy path: outside us-east-1 the
# module must refuse to plan at all.
run "certificate_outside_us_east_1_is_refused" {
  command = plan

  override_data {
    target = data.aws_region.current
    values = {
      id     = "sa-east-1"
      name   = "sa-east-1"
      region = "sa-east-1"
    }
  }

  expect_failures = [aws_acm_certificate.this]
}

# --- the two silent failure modes -------------------------------------------

run "xpi_objects_are_served_as_x_xpinstall" {
  command = plan

  assert {
    condition = alltrue([
      for object in values(aws_s3_object.release) : object.content_type == "application/x-xpinstall"
    ])
    error_message = "an .xpi object is not served as application/x-xpinstall; Firefox would refuse to install it"
  }

  assert {
    condition     = length(aws_s3_object.release) == 1
    error_message = "the fixture's .xpi was not picked up, so the content-type assertion above proved nothing"
  }
}

run "update_payload_lands_at_the_site_root" {
  command = plan

  assert {
    condition     = aws_s3_object.updates_manifest[0].key == "updates.json"
    error_message = "updates.json is not at the site root; every installed extension would silently stop updating"
  }

  assert {
    condition = alltrue([
      for object in values(aws_s3_object.release) : startswith(object.key, "releases/")
    ])
    error_message = "an .xpi is not under releases/ at the site root, so the update_link in updates.json would 404"
  }

  assert {
    condition = alltrue([
      for object in values(aws_s3_object.release) : length(split("/", object.key)) == 2
    ])
    error_message = "an .xpi key is nested below releases/, which the update_link does not address"
  }
}

run "update_payload_changes_are_content_addressed" {
  command = plan

  assert {
    condition = alltrue([
      for object in values(aws_s3_object.release) : object.source_hash == filemd5(object.source)
    ])
    error_message = "an .xpi does not use its content hash; byte changes at a stable source path would be missed"
  }

  assert {
    condition     = aws_s3_object.updates_manifest[0].source_hash == filemd5(aws_s3_object.updates_manifest[0].source)
    error_message = "updates.json does not use its content hash; byte changes at a stable source path would be missed"
  }
}

run "absolute_release_source_path_is_refused" {
  command = plan

  variables {
    release_source_dir = abspath("./tests/fixtures/site")
  }

  expect_failures = [var.release_source_dir]
}

# The manifest is what tells an installed extension where to fetch from. If it
# still advertises the old host after the cutover, publishing it here is worse
# than not publishing it at all.
run "stale_update_host_is_refused_once_the_domain_is_attached" {
  command = plan

  variables {
    release_source_dir   = "./tests/fixtures/stale-host"
    attach_custom_domain = true
  }

  expect_failures = [aws_s3_object.updates_manifest]
}

# --- bucket policies ---------------------------------------------------------
# Asserted against the local rather than a data source: aws_iam_policy_document
# is mocked away here, so asserting on its .json would prove nothing.

run "origin_is_readable_only_by_this_distribution" {
  command = plan

  # Both ARNs are assigned by AWS, so pin them to make the policy readable at
  # plan time instead of a wall of "known after apply".
  override_resource {
    target          = aws_cloudfront_distribution.this
    override_during = plan
    values = {
      arn = "arn:aws:cloudfront::699475944323:distribution/E2MOCKDIST"
    }
  }

  override_resource {
    target          = aws_s3_bucket.site
    override_during = plan
    values = {
      arn = "arn:aws:s3:::proso-site-699475944323"
    }
  }

  assert {
    condition = length([
      for s in jsondecode(local.site_bucket_policy).Statement :
      s if s.Effect == "Allow" && try(s.Principal.Service, null) != "cloudfront.amazonaws.com"
    ]) == 0
    error_message = "The origin bucket policy allows a principal other than CloudFront."
  }

  assert {
    condition = alltrue([
      for s in jsondecode(local.site_bucket_policy).Statement :
      try(s.Condition.StringEquals["AWS:SourceArn"], null) != null
      if s.Effect == "Allow"
    ])
    error_message = "The CloudFront grant is not bound to a source ARN, so any distribution in any account could read the origin."
  }
}

# The regression this catches was live on 25/08/2026: the module granted the
# delivery service a prefix it never writes to, AWS injected the statement it
# actually needed, and the next `terraform apply` planned to delete that
# statement — stopping log delivery with nothing in the plan saying so.
run "log_delivery_is_granted_the_prefix_aws_actually_writes_to" {
  command = plan

  override_resource {
    target          = aws_s3_bucket.logs
    override_during = plan
    values = {
      arn = "arn:aws:s3:::proso-site-699475944323-logs"
    }
  }

  override_resource {
    target          = aws_s3_bucket.site
    override_during = plan
    values = {
      arn = "arn:aws:s3:::proso-site-699475944323"
    }
  }

  override_resource {
    target          = aws_cloudwatch_log_delivery_source.cloudfront
    override_during = plan
    values = {
      arn = "arn:aws:logs:us-east-1:699475944323:delivery-source:proso-site-cf-access-logs"
    }
  }

  assert {
    condition = length([
      for s in jsondecode(local.logs_bucket_policy).Statement :
      s if try(s.Principal.Service, null) == "delivery.logs.amazonaws.com"
      && endswith(tostring(s.Resource), "/AWSLogs/699475944323/CloudFront/*")
    ]) == 1
    error_message = "The vended-log grant must target AWSLogs/<account>/CloudFront/*, the prefix CloudWatch Logs chooses; any other prefix grants nothing and leaves AWS to inject a statement the next apply deletes."
  }

  assert {
    condition = alltrue([
      for s in jsondecode(local.logs_bucket_policy).Statement :
      try(s.Condition.StringEquals["s3:x-amz-acl"], null) == "bucket-owner-full-control"
      if try(s.Principal.Service, null) == "delivery.logs.amazonaws.com"
    ])
    error_message = "The vended-log grant must require the bucket-owner-full-control ACL header, as the service sends it and as AWS's own injected statement does."
  }
}
