#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

readonly GENERATOR_FAMILY="${GENERATOR_FAMILY:-}"
readonly DETERMINISTIC_GATE="${DETERMINISTIC_GATE:-not supplied}"
readonly REQUESTED_REVIEWER="${ADVERSARIAL_REVIEWER:-default}"
readonly GROQ_API_KEY_FILE="${GROQ_API_KEY_FILE:-/run/secrets/groq_api_key}"
REPO_ROOT="$(git rev-parse --show-toplevel)"
readonly REPO_ROOT
TEMP_ROOT="$(mktemp -d -t proso-adversarial.XXXXXXXX)"
readonly TEMP_ROOT
readonly CHANGES_PATH="$TEMP_ROOT/changes.patch"
readonly CONTEXT_PATH="$TEMP_ROOT/context.txt"
readonly CURL_CONFIG_PATH="$TEMP_ROOT/curl.conf"
readonly ERROR_PATH="$TEMP_ROOT/reviewer.stderr"
readonly SCHEMA_PATH="$TEMP_ROOT/verdict.schema.json"
readonly PROMPT_PATH="$TEMP_ROOT/review-prompt.txt"
readonly RAW_PATH="$TEMP_ROOT/raw.json"
readonly VERDICT_PATH="$TEMP_ROOT/verdict.json"

cleanup() {
  rm -rf -- "$TEMP_ROOT"
}
trap cleanup EXIT INT TERM
chmod 700 "$TEMP_ROOT"

case "$GENERATOR_FAMILY" in
  openai)
    case "$REQUESTED_REVIEWER" in
      default | anthropic)
        readonly REVIEWER_FAMILY='anthropic'
        readonly REVIEWER_MODEL='claude-sonnet-5'
        ;;
      meta-llama)
        readonly REVIEWER_FAMILY='meta'
        readonly REVIEWER_MODEL='llama-3.3-70b-versatile'
        ;;
      *)
        printf 'OpenAI-generated work requires reviewer anthropic or meta-llama\n' >&2
        exit 2
        ;;
    esac
    ;;
  anthropic | zhipu)
    if [[ "$REQUESTED_REVIEWER" != 'default' && "$REQUESTED_REVIEWER" != 'openai' ]]; then
      printf '%s-generated work requires reviewer openai\n' "$GENERATOR_FAMILY" >&2
      exit 2
    fi
    readonly REVIEWER_FAMILY='openai'
    readonly REVIEWER_MODEL='gpt-5.6-terra'
    ;;
  *)
    printf 'GENERATOR_FAMILY must be openai, anthropic, or zhipu\n' >&2
    exit 2
    ;;
esac

cat >"$SCHEMA_PATH" <<'JSON'
{
  "type": "object",
  "additionalProperties": false,
  "required": ["verdict", "summary", "requirementTraces", "findings"],
  "properties": {
    "verdict": { "type": "string", "enum": ["PASS", "BLOCK"] },
    "summary": { "type": "string", "minLength": 80 },
    "requirementTraces": {
      "type": "array",
      "minItems": 6,
      "maxItems": 6,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["id", "requirement", "status", "evidence"],
        "properties": {
          "id": {
            "type": "string",
            "enum": ["REQ-1", "REQ-2", "REQ-3", "REQ-4", "REQ-5", "REQ-6"]
          },
          "requirement": { "type": "string", "minLength": 40 },
          "status": { "type": "string", "enum": ["PASS", "FAIL"] },
          "evidence": { "type": "string", "minLength": 80 }
        }
      }
    },
    "findings": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["severity", "file", "line", "problem", "fix"],
        "properties": {
          "severity": { "type": "string", "enum": ["critical", "high", "medium", "low"] },
          "file": { "type": "string", "minLength": 1 },
          "line": { "type": "integer", "minimum": 1 },
          "problem": { "type": "string", "minLength": 40 },
          "fix": { "type": "string", "minLength": 40 }
        }
      }
    }
  }
}
JSON

# A delivery review is always against origin/main, so the base is pinned here
# rather than inherited or read back from the receipt. Both of those were
# caller-controlled: `write-gate-receipt.sh` honours DIFF_BASE_REF, so an
# inherited `DIFF_BASE_REF=HEAD^` produced a parent-base receipt, satisfied a
# validator that expected the same inherited value, and then bundled only
# HEAD^..HEAD — a passing review of a fraction of the change.
readonly REVIEW_BASE_REF='origin/main'
GATE_RECEIPT="$(DIFF_BASE_REF="$REVIEW_BASE_REF" ./scripts/validate-gate-receipt.sh)"
readonly GATE_RECEIPT
DIFF_BASE_REF="$REVIEW_BASE_REF" ./scripts/change-bundle.sh "$CHANGES_PATH"
HEAD_SHA="$(git rev-parse HEAD)"
readonly HEAD_SHA
CHANGES_SHA="$(sha256sum "$CHANGES_PATH" | cut -d ' ' -f 1)"
readonly CHANGES_SHA

readonly RELEVANT_FILES=(Makefile docs/agent-delivery-harness.md)
if [[ "$REVIEWER_FAMILY" == 'meta' ]]; then
  context_instruction='Required unchanged files are inlined below.'
else
  context_instruction='Use read-only repository tools to read every required path below before verdict.'
fi
readonly context_instruction

for file in "${RELEVANT_FILES[@]}"; do
  if [[ ! -r "$file" ]]; then
    printf 'Required review context is unreadable: %s\n' "$file" >&2
    exit 1
  fi
  if [[ "$REVIEWER_FAMILY" == 'meta' ]]; then
    printf '\n===== RELEVANT FILE: %s =====\n' "$file" >>"$CONTEXT_PATH"
    cat -- "$file" >>"$CONTEXT_PATH"
  else
    printf '%s\n' "$file" >>"$CONTEXT_PATH"
  fi
done

{
  cat <<EOF
You are the fail-closed adversarial delivery reviewer for Proso.
The implementation was generated by the ${GENERATOR_FAMILY} model family; you are the
independent ${REVIEWER_FAMILY} family gate using exact model ${REVIEWER_MODEL}.

Deterministic gate evidence: ${DETERMINISTIC_GATE}
Bound receipt evidence: ${GATE_RECEIPT}
Reviewed candidate: HEAD=${HEAD_SHA}; change_bundle_sha256=${CHANGES_SHA}

Inspect the complete diff against ${REVIEW_BASE_REF}, including untracked files.
${context_instruction}
Trace every requirement to concrete code and test evidence:
REQ-1. The deterministic receipt binds the tested HEAD, exact base SHA, and exact tracked-plus-untracked
   change-bundle hash; missing, malformed, wrong-base, parent-SHA, or changed-diff receipts fail.
REQ-2. Coverage runs extension/server/gateway suites, requires every LCOV report, and blocks changed
   production lines below 80% without demanding an arbitrary whole-repository cleanup.
REQ-3. dependency-cruiser and changed-code jscpd block new boundary violations/cycles/clones while
   keeping classified legacy findings visible.
REQ-4. Knip and OSV baselines use stable fingerprints, owner/reason/issue/expiry metadata, and reject
   new, stale, malformed, or expired evidence.
REQ-5. OpenGrep fixtures prove workflow/test anti-defanging rules; Gitleaks scans the PR commit range
   plus the working tree; active docs reject expired ownership and broken relative links.
REQ-6. The implementation is the minimum local tool set, records licensing/eligibility skips, changes
   no workflow/production/release/deploy behavior, and makes no browser or production acceptance claim.

Treat malformed evidence, missing requirement traces, deterministic red checks, unverified claims,
or any material finding as BLOCK. PASS requires zero findings and every trace status PASS.
Return exactly one trace for each ID REQ-1 through REQ-6. Copy each requirement sentence above
verbatim into its requirement field. Every evidence string must name the exact supplied file and
the concrete assertion, command, or content that supports the status. Planted
violation results are recorded in docs/reading-journey-status.md; do not claim the review script
performs those mutations. Return only a JSON object matching the supplied schema. Do not use
Markdown fences.

===== REQUIRED JSON SCHEMA =====
EOF
  cat "$SCHEMA_PATH"
  cat <<'EOF'

===== COMPLETE CHANGE BUNDLE =====
EOF
  cat "$CHANGES_PATH"
  printf '\n===== REQUIRED REPOSITORY CONTEXT =====\n'
  cat "$CONTEXT_PATH"
} >"$PROMPT_PATH"

if [[ "$REVIEWER_FAMILY" == 'anthropic' ]]; then
  command -v claude >/dev/null 2>&1 || {
    printf 'claude is required for an Anthropic-family review\n' >&2
    exit 1
  }
  reviewer_status=0
  claude --print --model claude-sonnet-5 --effort max --permission-mode plan --safe-mode \
    --no-session-persistence --output-format json \
    --json-schema "$(tr -d '\n' <"$SCHEMA_PATH")" <"$PROMPT_PATH" >"$RAW_PATH" \
    2>"$ERROR_PATH" || reviewer_status=$?
  if [[ "$reviewer_status" -ne 0 ]]; then
    printf 'Anthropic reviewer failed before returning a verdict:\n' >&2
    if jq -e 'type == "object"' "$RAW_PATH" >/dev/null 2>&1; then
      jq '{type, subtype, is_error, result, error}' "$RAW_PATH" >&2
    else
      sed -n '1,20p' "$ERROR_PATH" >&2
    fi
    exit 1
  fi
  if ! jq -e '.structured_output // .structuredOutput' "$RAW_PATH" >"$VERDICT_PATH"; then
    printf 'Anthropic reviewer did not return structured output:\n' >&2
    jq '{type, subtype, is_error, result, error}' "$RAW_PATH" >&2
    exit 1
  fi
elif [[ "$REVIEWER_FAMILY" == 'openai' ]]; then
  command -v codex >/dev/null 2>&1 || {
    printf 'codex is required for an OpenAI-family review\n' >&2
    exit 1
  }
  reviewer_status=0
  codex exec --ephemeral --sandbox read-only --model gpt-5.6-terra --cd "$REPO_ROOT" \
    --output-schema "$SCHEMA_PATH" --output-last-message "$VERDICT_PATH" - <"$PROMPT_PATH" \
    >"$RAW_PATH" 2>"$ERROR_PATH" || reviewer_status=$?
  if [[ "$reviewer_status" -ne 0 ]]; then
    printf 'OpenAI reviewer failed before returning a verdict:\n' >&2
    sed -n '1,20p' "$ERROR_PATH" >&2
    exit 1
  fi
else
  for command_name in curl jq; do
    command -v "$command_name" >/dev/null 2>&1 || {
      printf '%s is required for a Meta-family review\n' "$command_name" >&2
      exit 1
    }
  done
  if [[ ! -r "$GROQ_API_KEY_FILE" ]]; then
    printf 'Meta-family review credential is unreadable: %s\n' "$GROQ_API_KEY_FILE" >&2
    exit 1
  fi

  groq_api_key="$(<"$GROQ_API_KEY_FILE")"
  : >"$CURL_CONFIG_PATH"
  chmod 600 "$CURL_CONFIG_PATH"
  printf 'header = "Authorization: Bearer %s"\n' "$groq_api_key" >"$CURL_CONFIG_PATH"
  unset groq_api_key
  jq -n \
    --arg model "$REVIEWER_MODEL" \
    --rawfile prompt "$PROMPT_PATH" \
    '{
      model: $model,
      temperature: 0,
      max_completion_tokens: 8000,
      response_format: { type: "json_object" },
      messages: [{ role: "user", content: $prompt }]
    }' >"$RAW_PATH.request"

  reviewer_status=0
  curl --fail-with-body --silent --show-error --max-time 300 \
    --config "$CURL_CONFIG_PATH" \
    -H 'Content-Type: application/json' \
    --data-binary "@$RAW_PATH.request" \
    https://api.groq.com/openai/v1/chat/completions >"$RAW_PATH" \
    2>"$ERROR_PATH" || reviewer_status=$?
  if [[ "$reviewer_status" -ne 0 ]]; then
    printf 'Meta reviewer failed before returning a verdict:\n' >&2
    if jq -e 'type == "object"' "$RAW_PATH" >/dev/null 2>&1; then
      jq '{error}' "$RAW_PATH" >&2
    else
      sed -n '1,20p' "$ERROR_PATH" >&2
    fi
    exit 1
  fi
  if ! jq -e --arg model "$REVIEWER_MODEL" '.model == $model' "$RAW_PATH" >/dev/null; then
    printf 'Meta reviewer response did not identify exact model %s\n' "$REVIEWER_MODEL" >&2
    exit 1
  fi
  if ! jq -er '.choices[0].message.content' "$RAW_PATH" \
    | jq -e '.' >"$VERDICT_PATH"; then
    printf 'Meta reviewer returned malformed structured output.\n' >&2
    exit 1
  fi
fi

jq -e '
  {
    "REQ-1": "The deterministic receipt binds the tested HEAD, exact base SHA, and exact tracked-plus-untracked change-bundle hash; missing, malformed, wrong-base, parent-SHA, or changed-diff receipts fail.",
    "REQ-2": "Coverage runs extension/server/gateway suites, requires every LCOV report, and blocks changed production lines below 80% without demanding an arbitrary whole-repository cleanup.",
    "REQ-3": "dependency-cruiser and changed-code jscpd block new boundary violations/cycles/clones while keeping classified legacy findings visible.",
    "REQ-4": "Knip and OSV baselines use stable fingerprints, owner/reason/issue/expiry metadata, and reject new, stale, malformed, or expired evidence.",
    "REQ-5": "OpenGrep fixtures prove workflow/test anti-defanging rules; Gitleaks scans the PR commit range plus the working tree; active docs reject expired ownership and broken relative links.",
    "REQ-6": "The implementation is the minimum local tool set, records licensing/eligibility skips, changes no workflow/production/release/deploy behavior, and makes no browser or production acceptance claim."
  } as $expected
  | type == "object"
  and (.verdict == "PASS" or .verdict == "BLOCK")
  and (.summary | type == "string" and length >= 80)
  and (.requirementTraces | type == "array" and length == 6)
  and (all(.requirementTraces[];
    (.id | type == "string")
    and (.status == "PASS" or .status == "FAIL")
    and (.requirement == $expected[.id])
    and (.evidence | type == "string" and length >= 80)
    and (.evidence | test("([[:alnum:]_.-]+/)+[[:alnum:]_.-]+"))))
  and (([.requirementTraces[].id] | sort) ==
    ["REQ-1", "REQ-2", "REQ-3", "REQ-4", "REQ-5", "REQ-6"])
  and (.findings | type == "array")
  and (all(.findings[];
    (.severity == "critical" or .severity == "high" or .severity == "medium" or .severity == "low")
    and (.file | type == "string" and length > 0)
    and (.line | type == "number" and . >= 1)
    and (.problem | type == "string" and length >= 40)
    and (.fix | type == "string" and length >= 40)))
' "$VERDICT_PATH" >/dev/null || {
  printf 'Adversarial reviewer returned a malformed verdict:\n' >&2
  jq . "$VERDICT_PATH" >&2
  exit 1
}

jq . "$VERDICT_PATH"

if ! jq -e '
  .verdict == "PASS"
  and (.findings | length == 0)
  and all(.requirementTraces[]; .status == "PASS")
' "$VERDICT_PATH" >/dev/null; then
  printf 'Adversarial review blocked delivery.\n' >&2
  exit 1
fi
